Repository woocommerce/woocommerce-accommodation-bookings, pull requests merged in 2023-10, with the labels that each got.

#362 Assets: Hard code the paths to the asset data files
  includes/class-wc-accommodation-bookings-plugin.php
Labels: changelog: none, needs: qit security test

#379 Release/1.2.1
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-accommodation-bookings.php
Labels: needs: qit default tests, needs: e2e testing

#371 Set up e2e tests utilizing Playwright
  .gitattributes
  .github/workflows/e2e.yml
  .gitignore
  .wp-env.json
  package-lock.json
  package.json
  tests/e2e/bin/initialize.sh
  tests/e2e/bin/install-plugins.sh
  tests/e2e/bin/wp-cli.yml
  tests/e2e/config/index.js
  tests/e2e/global-setup.js
  tests/e2e/global-teardown.js
  tests/e2e/playwright.config.js
  tests/e2e/specs/admin.spec.js
  tests/e2e/specs/order.spec.js
  tests/e2e/specs/product.spec.js
  tests/e2e/utils/api.js
  tests/e2e/utils/index.js
Labels: status: e2e tests passing
