Repository woocommerce/woocommerce-accommodation-bookings, pull requests merged in 2024-07, with the labels that each got.

#446 Bump WordPress 'Tested up to' version 6.6
  readme.txt
  woocommerce-accommodation-bookings.php
Labels: status: e2e tests passing, needs: WP RC test

#450 Release/1.2.7
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-accommodation-bookings.php
Labels: needs: qit default tests, status: e2e tests passing

#451 Compatibility testing with Woo 9.1
  woocommerce-accommodation-bookings.php
Labels: status: e2e tests passing
